INSERT INTO characters (name, status, first_appearance, description)
VALUES
    ('Rick Grimes', 'Alive', 'Season 1, Episode 1', 'Former Sheriff''s deputy who leads a group of survivors.'),
    ('Daryl Dixon', 'Alive', 'Season 1, Episode 3', 'Expert hunter, tracker, and archer.'),
    ('Negan', 'Alive', 'Season 6, Episode 16', 'Former antagonist turned ally, known for his use of a bat named Lucille.'),
    ('Carol Peletier', 'Alive', 'Season 1, Episode 3', 'A pragmatic and strong-willed survivor who has overcome personal loss.'),
    ('Glenn Rhee', 'Deceased', 'Season 1, Episode 2', 'Resourceful and brave, Glenn grew from a likable scavenger to a key leader.'),
    ('Maggie Rhee', 'Alive', 'Season 2, Episode 2', 'Determined and strong, Maggie becomes a leader following the death of her father and husband.'),
    ('Michonne', 'Alive', 'Season 3, Episode 3', 'Fierce and stoic, skilled with a katana and troubled by her past.'),
    ('Hershel Greene', 'Deceased', 'Season 2, Episode 2', 'The moral center of the group, a veterinarian and farmer who values life.'),
    ('Shane Walsh', 'Deceased', 'Season 1, Episode 1', 'Rick''s best friend and a complex character torn between protecting the group and his own desires.'),
    ('Beth Greene', 'Deceased', 'Season 2, Episode 2', 'Hershel''s youngest daughter, known for her kind heart and singing.'),
    ('Tyreese Williams', 'Deceased', 'Season 3, Episode 8', 'Strong and compassionate, struggles with the moral complexities of the post-apocalyptic world.'),
    ('Sasha Williams', 'Deceased', 'Season 3, Episode 8', 'A fiery and strong-willed survivor who faces numerous personal losses.'),
    ('Abraham Ford', 'Deceased', 'Season 4, Episode 10', 'A former military man who is effective in combat but struggles with the emotional fallout of the apocalypse.'),
    ('Eugene Porter', 'Alive', 'Season 4, Episode 10', 'A man who initially lies about knowing a cure to the zombie plague to ensure his survival.'),
    ('Rosita Espinosa', 'Alive', 'Season 4, Episode 10', 'Tough and capable, but also has deep emotions and vulnerabilities.'),
    ('Gabriel Stokes', 'Alive', 'Season 5, Episode 2', 'A priest who battles with his faith and guilt in a world overrun by the undead.'),
    ('Aaron', 'Alive', 'Season 5, Episode 10', 'A recruiter for the Alexandria Safe-Zone who is optimistic and skilled in diplomacy.'),
    ('Paul Rovia', 'Deceased', 'Season 6, Episode 10', 'A resourceful scout and fighter, known for his tactical genius and long hair.'),
    ('Morgan Jones', 'Alive', 'Season 1, Episode 1', 'Struggles with his sanity but evolves into a pacifist who believes all life is precious.'),
    ('King Ezekiel', 'Alive', 'Season 7, Episode 2', 'Leader of the Kingdom, a community known for its positive outlook and theatrical speech.'),
    ('Alpha', 'Deceased', 'Season 9, Episode 6', 'The menacing leader of the Whisperers, known for wearing a mask made of human skin.'),
    ('Beta', 'Deceased', 'Season 9, Episode 12', 'Second-in-command of the Whisperers, fiercely loyal to Alpha.'),
    ('Lydia', 'Alive', 'Season 9, Episode 6', 'Daughter of Alpha, struggles with her loyalty between her mother and her new friends.'),
    ('Gregory', 'Deceased', 'Season 5, Episode 11', 'Former leader of the Hilltop, known for his cowardice and scheming.'),
    ('Simon', 'Deceased', 'Season 6, Episode 8', 'One of Negan''s top lieutenants, brutal and ambitious.'),
    ('Enid', 'Deceased', 'Season 5, Episode 12', 'A young and resourceful survivor who grows close to Carl and Maggie.'),
    ('Spencer Monroe', 'Deceased', 'Season 5, Episode 12', 'Resident of Alexandria, known for his questionable decisions and attempts to undermine Rick.'),
    ('Jessie Anderson', 'Deceased', 'Season 5, Episode 12', 'A resident of Alexandria who forms a close bond with Rick.'),
    ('Tara Chambler', 'Deceased', 'Season 4, Episode 6', 'A tough and moral character who originally arrives with the Governor''s group.'),
    ('Noah', 'Deceased', 'Season 5, Episode 4', 'A young man who survives through intelligence and speed, ultimately faces a tragic end.'),
    ('Bob Stookey', 'Deceased', 'Season 4, Episode 1', 'A former army medic haunted by his past, known for his optimism.'),
    ('Siddiq', 'Deceased', 'Season 7, Episode 6', 'A doctor who survives immense trauma and strives to uphold his father’s principles.'),
    ('Lori Grimes', 'Deceased', 'Season 1, Episode 1', 'Rick''s wife, whose relationships and decisions impact the early group dynamics.'),
    ('Andrea', 'Deceased', 'Season 1, Episode 2', 'A former civil rights attorney and a strong survivor, her arc dramatically shifts across the seasons.'),
    ('Dale Horvath', 'Deceased', 'Season 1, Episode 2', 'An elder statesman of the group, known for his wisdom and moral perspective.'),
    ('Phillip Blake', 'Deceased', 'Season 3, Episode 3', 'A charismatic leader with a brutal approach to maintaining control.'),
    ('Merle Dixon', 'Deceased', 'Season 1, Episode 2', 'Daryl''s volatile older brother, known for his rough demeanor and complex loyalty.'),
    ('Milton Mamet', 'Deceased', 'Season 3, Episode 3', 'A scientist working for the Governor, fascinated by the walkers.'),
    ('Jacqui', 'Deceased', 'Season 1, Episode 2', 'A member of the original Atlanta group, known for her rational decisions.'),
    ('Paula', 'Deceased', 'Season 6, Episode 13', 'Member of the Saviors, encountered by Maggie and Carol.'),
    ('Oscar', 'Deceased', 'Season 3, Episode 2', 'One of the prisoners who survived in the prison.'),
    ('Axel', 'Deceased', 'Season 3, Episode 2', 'A prisoner who tries to integrate into the group.'),
    ('Tobin', 'Deceased', 'Season 5, Episode 5', 'A construction foreman in Alexandria who later becomes involved with Carol.'),
    ('Eric Raleigh', 'Deceased', 'Season 5, Episode 11', 'Aaron’s partner and a recruiter for Alexandria.'),
    ('Denise Cloyd', 'Deceased', 'Season 6, Episode 2', 'A doctor in Alexandria who takes over after Pete’s death.'),
    ('Dwight', 'Alive', 'Season 6, Episode 6', 'A former high-ranking member of the Saviors who defects.'),
    ('Heath', 'Unknown', 'Season 6, Episode 1', 'A supply runner from Alexandria, whose fate remains uncertain.'),
    ('Olivia', 'Deceased', 'Season 5, Episode 12', 'Responsible for the pantry and armory in Alexandria.'),
    ('Eastman', 'Deceased', 'Season 6, Episode 4', 'A psychiatrist who teaches Morgan the art of Aikido.'),
    ('Samuel', 'Deceased', 'Season 4, Episode 2', 'A young boy from the prison who succumbs to the infection.'),
    ('Lizzie Samuels', 'Deceased', 'Season 4, Episode 1', 'A troubled child who does not understand the nature of walkers.'),
    ('Mika Samuels', 'Deceased', 'Season 4, Episode 1', 'Lizzie’s younger sister, more realistic about walkers.'),
    ('Edwin Jenner', 'Deceased', 'Season 1, Episode 5', 'A CDC scientist the group encounters in Atlanta.'),
    ('Joe', 'Deceased', 'Season 4, Episode 11', 'Leader of the Claimers, a dangerous and ruthless group.'),
    ('Carter', 'Deceased', 'Season 6, Episode 1', 'An Alexandrian who disagrees with Rick’s leadership.'),
    ('Nicholas', 'Deceased', 'Season 5, Episode 12', 'An Alexandrian who clashes with Glenn.'),
    ('Pete Anderson', 'Deceased', 'Season 5, Episode 12', 'The abusive surgeon of Alexandria.'),
    ('Deanna Monroe', 'Deceased', 'Season 5, Episode 12', 'Former leader of Alexandria before Rick’s arrival.'),
    ('Reg Monroe', 'Deceased', 'Season 5, Episode 12', 'Deanna’s husband, an architect who designed Alexandria’s walls.'),
    ('Sam Anderson', 'Deceased', 'Season 5, Episode 12', 'Jessie’s young son who becomes fearful of the walkers.'),
    ('Ron Anderson', 'Deceased', 'Season 5, Episode 12', 'Jessie’s older son who harbors anger towards Rick and Carl.'),
    ('Carl Grimes', 'Deceased', 'Season 1, Episode 1', 'Rick’s son and a badass kid.'),
    ('Owen', 'Deceased', 'Season 6, Episode 8', 'A member of the Wolves who captures Denise.'),
    ('Sherry', 'Alive', 'Season 6, Episode 6', 'Dwight’s wife who also defects from the Saviors.'),
    ('Francine', 'Deceased', 'Season 5, Episode 14', 'A tough worker in Alexandria who survives a walker attack.'),
    ('Jadis Stokes', 'Deceased', 'Season 7, Episode 10', 'Leader of the Scavengers, known for her unique way of speaking.'),
    ('Tamiel', 'Deceased', 'Season 7, Episode 8', 'A member of the Scavengers, loyal to Jadis.'),
    ('Henry Sutton', 'Deceased', 'Season 7, Episode 2', 'A young member of the Kingdom who looks up to King Ezekiel.'),
    ('Cyndie', 'Alive', 'Season 7, Episode 6', 'A resident of Oceanside, seeking revenge against the Saviors.')

ON CONFLICT DO NOTHING;
