INSERT INTO character_memorable_quotes (character_id, quote)
VALUES
    (1, 'We are the walking dead.'),
    (1, 'You kill or you die, or you die and you kill.'),
    (2, 'I ain''t nobody''s bitch.'),
    (2, 'I''m not right, but that doesn''t make me wrong.'),
    (3, 'I hope you got your shittin'' pants on.'),
    (3, 'I am Negan.'),
    (4, 'Look at the flowers.'),
    (4, 'Just look at the flowers, Lizzie.'),
    (5, 'Maggie, I''ll find you.'),
    (5, 'I will not be afraid of my own people.'),
    (6, 'Good thing we''re here.'),
    (6, 'We''re the ones who live.'),
    (7, 'My mercy prevails over my wrath.'),
    (7, 'I can''t help you if you won''t let me.'),
    (8, 'I''m just another monster too.'),
    (8, 'I deserve to die, Rick. Me! Not you, not Carl, not the baby. Me!'),
    (9, 'Every sacrifice we make needs to be for the greater good.'),
    (9, 'The day will come when they''ll wish they''d killed us.'),
    (10, 'I''m not the good guy anymore.'),
    (10, 'It''s always the children who suffer.'),
    (11, 'We''re not just doing this for us. We''re doing it for the future.'),
    (11, 'I am not staying down here.'),
    (12, 'No one''s keeping score, brother.'),
    (12, 'Well, bite my nutsack.'),
    (13, 'You step outside, you risk your life. You take a drink of water, you risk your life. Nowadays you breathe and you risk your life.'),
    (13, 'I ain''t gonna beg.'),
    (14, 'I just need to pull my head out of my ass.'),
    (14, 'I''m here to help.'),
    (15, 'The world''s gonna change.'),
    (15, 'It''s a long life, and then it isn''t.'),
    (16, 'Fake it ''til you make it, baby.'),
    (16, 'We are one.'),
    (17, 'They''re messin'' with the wrong people.'),
    (17, 'When you care about people, hurt is kinda part of the package.'),
    (18, 'You''re part of the problem, not the solution.'),
    (18, 'I''m not gonna kill you. Maybe you''ll learn.'),
    (19, 'No one gets to clock out today.'),
    (19, 'I won''t have you dying for nothing.'),
    (20, 'You''re not seeing things right, but you will.'),
    (21, 'And yet I smile.'),
        (22, 'We are the end of the world.'),
        (23, 'My Alpha.'),
        (24, 'I don''t belong with them.'),
        (25, 'I didn''t want this.'),
        (26, 'We''re all Negan.'),
        (27, 'Just survive somehow.'),
        (28, 'I''m trying to save this place.'),
        (29, 'We''ll make it work.'),
        (30, 'I got this.'),
        (31, 'We stick together.'),
        (32, 'Nightmares end.'),
        (33, 'My mom told me to honor you.'),
        (34, 'We don''t kill the living.'),
        (35, 'They''re screwing with the wrong people.'),
        (36, 'We let go of all of it.'),
        (37, 'You can''t just be the good guy and expect to live, okay? Not anymore.'),
        (38, 'I ain''t beggin'' ya.'),
        (39, 'People adapt. Our will to live surpasses our survival instinct.'),
        (40, 'It''s the brain. It''s always the brain.'),
        (41, 'We are all Negan.'),
        (42, 'It''s just us now.'),
        (43, 'I''m telling you, you guys got it made.'),
        (44, 'You keep that hair short.'),
        (45, 'We''ll be okay.'),
        (46, 'You''re not gonna find anyone with less experience.'),
        (47, 'We can''t do it. But we can try.'),
        (48, 'People don''t trust you if you try too hard.'),
        (49, 'I can''t believe I just said that.'),
        (50, 'That is the cheesiest damn thing I ever heard.'),
        (51, 'Mama?'),
        (52, 'Just look at the flowers.'),
        (53, 'We don''t get to be upset.'),
        (54, 'It''s all about staying alive now.'),
        (55, 'Ain''t nobody got to die today.'),
        (56, 'It''s always the same with you, Rick. You''re always looking for problems.'),
        (57, 'I''m just trying to keep this place safe.'),
        (58, 'You wanna tell me what this is about?'),
        (59, 'We have to come for them before they come for us.'),
        (60, 'We don''t need to fight.'),
        (61, 'Mom, where are you?')
